config/routes.rb
Rails.application.routes.draw do
  get 'photos/index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "pages#index"

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts do 
  	resources :postcomments
  end

   resources :photos 
   
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
has_many :photos
end

app/models/photo.rb
class Photo < ApplicationRecord
mount_uploader :photo, PhotoUploader
belongs_to :user
belongs_to :category
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :postcomments
  
  validates :title, :body, presence: true
  validates :title, length: { in: 1..10 }
  

end

app/models/postcomment.rb
class Postcomment < ApplicationRecord
	validates :text, presence: true
  	validates :text, length: { in: 5..255 }
	belongs_to :user
	belongs_to :post
	validates :text, presence: true
  	validates :text, length: { in: 3..255 }
  	validates :text, exclusion: { in: [nil] }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  validates :nickname, :password, :email, presence: true
  validates :nickname, length: { in: 5..15 }
  validates :nickname, format: { with: /\A[a-zA-Z]+\z/,
    message: "only allows letters" }

 devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
  has_many :postcomments
  has_many :photos
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/default.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :devise_sign_up_params, if: :devise_controller?
	protect_from_forgery with: :exception

	private

	def devise_sign_up_params
		devise_parameter_sanitizer.permit(:sign_up, keys:[:attribute, :nickname, :avatar])
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  	@users = User.all
    @posts = Post.all
  end
  def contact
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
  	@photos = Photo.all
  end

  def new
  	@photo = Photo.new
  end

  def create
  	params[:photo][:category_id] = params[:category_id]
  	params[:photo][:user_id] = current_user.id
  	@photo = Photo.create(photo_params)
  	redirect_to photos_path
  end

  def edit
  end

  def update
  end

  def destroy
  end

private

	def photo_params
		params.require(:photo).permit(:user_id, :category_id, :name, :photo)
	end

end

app/controllers/postcomments_controller.rb
class PostcommentsController < ApplicationController
before_action :authenticate_user!

def create
params[:postcomment][:post_id]=params[:post_id]
params[:postcomment][:user_id]=current_user.id
@comment=Postcomment.create(postcomments_params)
if @comment.save
	redirect_to post_path(params[:post_id])
else
	@comment.errors.full_messages.each do |msg|
		@msg=msg
end
flash[:notice]="#{@msg}"
redirect_to post_path(params[:post_id])
end
end

private
def postcomments_params
 	params.require(:postcomment).permit(:user_id, :post_id, :text)
end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_action :authenticate_user!
before_action :set_post, only: [:show, :edit, :update, :destroy]

  def show
   @comments = Postcomment.where(post_id: @post.id)
  end

  def new
  @post = Post.new
  end
  
  def create
  @post = current_user.posts.build(post_params)
  if @post.save
       redirect_to root_path
      else
          render 'new'
  end
  end

  def edit


  end


  def update    
  @post.update(post_params)
         redirect_to root_path
  end


  def destroy
    @post.destroy
    redirect_to root_path
  end



  private 

def post_params
    params.require(:post).permit(:user_id, :title, :body, :text)
 end


 def set_post 
     @post = Post.find(params[:id])

end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/postcomments_helper.rb
module PostcommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_footer.html.erb
<style type="text/css">
  footer{
    height: 35px;
    width: 100%;
    background: #373a42;
    height: 28px;
    background: black;
    text-align: center;
    position: fixed;
    bottom: 0;
    left: 0;
    right: 0;
    color: #ddd;
    font-size: 16px;
    font-size: 8;
  }
</style>
<hr>
<footer>
    Made by Vasyl Lukachynets
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to "Blog" , root_path , class: "navbar-brand" %>
    </div>
   

    <ul class="nav navbar-nav navbar-right">
    <% if current_user.nil? %>
    <li>
    <%= link_to user_session_path do %>
      <i class="glyphicon glyphicon-user"></i> Login
      <%end%>
      </li>
      <% else %> 
      <li>
      <%= link_to destroy_user_session_path, method: :delete do %>
      <i class="glyphicon glyphicon-log-in"></i> Logout
  <%end%>
      </li>
       <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogger</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
  	<%= render 'layouts/navbar'%>
    <div class="container">
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>
  </body>
</html>

app/views/pages/index.html.erb
<%= link_to "Create new post" , new_post_path , class: "btn btn-info"%>
<%= link_to "Show Gallery" , photos_path , class: "btn btn-info"%>
<hr>
<div>
<% @posts.each do |post| %>
  <h1><%= link_to post.title, post_path(post.id) %></h1> 
  <div><%= sanitize post.body %></div> 
  
  <p>
  <%= image_tag post.user.avatar.url(:thumb), width: 30, heigth: 30 %>
  Author: <%= post.user.nickname %> | 
  Created at: <%= post.created_at %>
  </p>

  <% if current_user != nil and current_user.id == post.user_id %>
    <p><%= link_to "Edit", edit_post_path(post.id)%> |  
     <%= link_to "Delete", post_path(post.id), data: {confirm: 'Are you sure?'}, method: :delete %> </p>
  <%end%>
  <hr>
<%end %>
</div>

app/views/photos/_form.html.erb
<p><%= f.label :category %></p>
<%= select_tag 'category_id', options_from_collection_for_select(Category.all, 'id', 'name') %>
<p><%= f.label :name %></p>
<%= f.text_field :name %><br />

<p><%= f.label "Upload photo" %></p>
<%= f.file_field :photo %>

<p><%= f.submit "Save" %></p>

app/views/photos/index.html.erb
<%= link_to "Upload new photo" , new_photo_path , class: "btn btn-info"%>
<hr>
<% if @photos == [] %>
	<p>Nukyc</p>
<% else %>
	<% @photos.each do |photo|%>
		<%= image_tag(photo.photo_url) %>
		<%= photo.name%>
	<% end %>
<% end %>

app/views/photos/new.html.erb
<%= form_for @photo, url:photos_path do |f| %>

<%= render 'photos/form', f:f %>


<%end%>

app/views/posts/_form.html.erb
<p><%= f.label :title %></p>
<%= f.text_field :title %><br />

<p><%= f.label :body %></p>
<%= f.text_area :body, :class => "tinymce", :rows => 40, :cols => 120 %>
<%= tinymce %>
<p><%= f.submit "Save" %></p>

app/views/posts/edit.html.erb
<%= form_for :post, url:post_path, method: :patch do |f| %>
 <% if @post.errors.any?  %>
   <% @post.errors.full_messages.each do |msg| %>
   <li><%= msg%></li>
   <%end%>
   <%end%>


<%= render 'posts/form', f:f %>



<%end%>

app/views/posts/new.html.erb
<%= form_for @post, url:posts_path, validate: true do |f| %>
 <% if @post.errors.any?  %>
   <% @post.errors.full_messages.each do |msg| %>
   <li><%= msg%></li>
   <%end%>
   <%end%>


<%= render 'posts/form', f:f %>


<%end%>

app/views/posts/show.html.erb
<style>
div1 {
    border: 2px solid #a1a1a1;
    padding: 10px 40px; 
    background: #dddddd;
    width: 300px;
    border-radius: 25px;
}
</style>

<h1><%= @post.title%></h1>
<div1><%= sanitize @post.body%></div1>
<hr>
<% @comments.each do |comment| %> 
<p>comment by user <%= comment.user.nickname %> :</p>
<%= comment.text %>
<hr>
<% end %>

<%= form_for :postcomment, url:post_postcomments_path(post_id: @post.id) do |f| %>
<% if flash[:notice] %>
	<div class="notice"><%= flash[:notice] %></div>
<%end%>

<p><%= f.label "What do you think about it?"%></p>
<%= f.text_area :text, cols: 10, rows: 3 %><br />

<p><ul><li><%= f.submit "Reply", class: "btn btn-primary"%></li></ul></p>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>